### PR TITLE
Added feature for layerLists

### PR DESCRIPTION
**Pull request by indra-ehep**
Added feature for layerList, this linked to PR 39774 of https://github.com/cms-sw/cmssw

### CODE REVIEW

**Comment by smuzaffar** [comment]
@indra-ehep contents of this repository are generated from cmssw generated cfipython files. So changes should go in to https://github.com/cms-sw/cmssw

**Comment by indra-ehep** [comment]
@smuzaffar : Actually I could not find cfipython directory under https://github.com/cms-sw/cmssw . Is it inside some subfolder ?

**Comment by smuzaffar** [comment]
@indra-ehep , you need to update https://github.com/cms-sw/cmssw/blob/master/Validation/HGCalValidation/test/HGCalCellHitSum.cc#L1170-L1178 section

**Comment by indra-ehep** [comment]
Thank you for your response. It is there in new commit in cmssw as you have
already spotted in other PR.

**Pull request closed without merging**
